### ISSUE TITLE
Get the tool running in your environment.

### ISSUE THREAD

**Issue by mshakya** [bos-lab/piret#1]
- Try installing PiReT and get it running in your environment.

**Comment by Andreas-Martinez** [comment]
- Tool runs successfully to completion with PIRET test files but R error when running on intoxication samples in heatmap and some other graphic creation

NEXT STEPS
troubleshoot R error. Might have to to with graphics capabilities or libcurl

**Comment by Andreas-Martinez** [comment]
Completed. 

-  Solution to .png capabilities error is to comment out all .png lines. PDF creation still works.

- Also fixed a change in syntax due to versioning
    `for (n in 1:length(all_pairs) ) {` to `for (n in 1:nrow(all_pairs) ) {`
and   indexing from `all_pairs[[n]][1]` to `all_pairs[n, 1]`
